r"""
One-dimensional heat diffusion in a semi-infinite rod.

This module provides a toy inverse problem for reconstructing the
time-dependent boundary temperature of a semi-infinite rod from
temperature measurements taken far from the boundary.

Physical model
--------------
Consider a homogeneous rod occupying :math:`x\geq 0`, with constant
thermal diffusivity :math:`\alpha`. Assuming one-dimensional heat
conduction, the temperature satisfies

.. math::

    \frac{\partial T(x,t)}{\partial t}
    =
    \alpha\frac{\partial^2 T(x,t)}{\partial x^2},
    \qquad x>0,\quad t>0.

The rod is initially at a known uniform temperature :math:`T_0`:

.. math::

    T(x,0)=T_0,\qquad x>0.

The boundary temperature is an unknown function :math:`T_s(t)`:

.. math::

    T(0,t)=T_s(t),\qquad t>0.

Far from the boundary, the temperature approaches its initial value:

.. math::

    \lim_{x\to\infty}T(x,t)=T_0.

Measurements are taken at a fixed position :math:`x_m>0`. The inverse
problem consists of reconstructing the boundary-temperature history
:math:`T_s(t)` from the measured temperature history :math:`T(x_m,t)`.
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy
import warnings
from pyregtools.utils import add_gaussian_noise

class TempSemiInfRod:
    r"""
    Discrete inverse problem for boundary-temperature reconstruction.

    The class implements the analytical forward response, the heat
    kernel, and a discrete sensing matrix for a semi-infinite rod.
    It also provides several boundary-temperature histories and methods
    for generating noiseless and noisy measurements.

    Notes
    -----
    **Analytical solution**

    For a boundary-temperature step applied at time :math:`t_s`, the
    temperature measured at :math:`x_m` is

    .. math::

        T(x_m,t)
        =
        T_0
        +
        (T_{\mathrm{source}}-T_0)
        \operatorname{erfc}
        \left(
            \frac{x_m}{2\sqrt{\alpha(t-t_s)}}
        \right),

    for :math:`t>t_s`. Before and at the step time, the temperature at
    the measurement position equals :math:`T_0`.

    This analytical solution is implemented in
    :meth:`temp_analytical_step` and provides a reference for validating
    the discrete forward model.

    **Convolution integral**

    For a general boundary-temperature history, define the temperature
    rises

    .. math::

        u(t)=T_s(t)-T_0,

    and

    .. math::

        y(t)=T(x_m,t)-T_0.

    The forward problem is expressed as a causal convolution:

    .. math::

        y(t)
        =
        \int_0^t K(x_m,t-s)u(s)\,ds,

    where the heat kernel is

    .. math::

        K(x_m,\tau)
        =
        \frac{x_m}{2\sqrt{\pi\alpha}\,\tau^{3/2}}
        \exp\left(
            -\frac{x_m^2}{4\alpha\tau}
        \right),
        \qquad \tau>0.

    The kernel vanishes for :math:`\tau\leq 0`.

  
    .. list-table::
       :header-rows: 1
       :widths: 20 15 65

       * - Attribute
         - Type / shape
         - Description
       * - ``xm``
         - float
         - Measurement distance from the boundary, in m.
       * - ``alpha``
         - float
         - Thermal diffusivity, in m²/s.
       * - ``T0``
         - float
         - Initial uniform temperature of the rod, in K.
       * - ``fs``
         - int
         - Sampling frequency, in Hz.
       * - ``time``
         - ndarray, (N,)
         - Measurement times and edges of the source intervals, in s.
       * - ``A``
         - ndarray, (N, N-1)
         - Sensing matrix constructed by ``sens_mtx``.
       * - ``x_true``
         - ndarray, (N-1,)
         - Absolute boundary-temperature history generated by a source method, in K.
       * - ``b_true``
         - ndarray, (N,)
         - Noiseless absolute temperature measurements, in K.
       * - ``b_noisy``
         - ndarray, (N,)
         - Noisy absolute temperature measurements, in K.

    Parameters
    ----------
    xm : float, default=1.0
        Distance from the boundary to the measurement position, in m.
        Must be positive.
    alpha : float, default=1.0
        Thermal diffusivity of the rod, in m²/s. Must be positive.
    T0 : float, default=100.0
        Initial uniform temperature of the rod, in K.
    tmax : float, default=10.0
        Upper limit of the time interval, in s. The endpoint is
        excluded from the generated time vector.
    fs : int, default=50
        Sampling frequency, in Hz.
    """
    def __init__(self, xm=1.0, alpha = 1.0, T0 = 100, tmax = 10, fs = 50):
        """
        """
        if xm <= 0:
            warnings.warn("Measurement location should be greater than 0. I'll set to 1.0 [m].")
            xm = 1.0
        self.xm = xm

        if alpha <= 0:
            warnings.warn("Diffusion coefficient should be positive. I'll set to 1.0.")
            alpha = 1
        self.alpha = alpha

        if T0 < 0:
            warnings.warn("Initial temperatude should be 0 or greater. I'll set to 0 [K].")
            T0 = 0
        self.T0 = T0

        if not isinstance(fs, int) and fs<0:
            warnings.warn("Sampling frequency should be an integer positive. I'll set to 50.")
            fs = 50
        self.fs = fs

        self.time = np.arange(0, tmax, 1/fs) # time vector of measurement

    def temp_analytical_step(self, time_step=0.0, T_source=400.0):
        r"""
        Compute the analytical temperature response to a boundary step.

        Evaluates the exact solution of the one-dimensional heat equation
        in a semi-infinite rod, initially at a uniform temperature
        :math:`T_0`. At time :math:`t_s`, the boundary temperature changes
        from :math:`T_0` to :math:`T_{\mathrm{source}}`.

        Parameters
        ----------
        time_step : float, default=0.0
            Time :math:`t_s` at which the boundary temperature changes,
            in s.
        T_source : float, default=400.0
            Boundary temperature after the step, in K.

        Returns
        -------
        b_analytical : ndarray, shape (N,)
            Analytical temperature history at the measurement position
            :math:`x_m`, evaluated at the :math:`N` measurement times,
            in K.

        Notes
        -----
        For :math:`t>t_s`, the analytical solution at the measurement
        position is

        .. math::

            T(x_m,t)
            =
            T_0
            +
            (T_{\mathrm{source}}-T_0)
            \operatorname{erfc}
            \left(
                \frac{x_m}{2\sqrt{\alpha(t-t_s)}}
            \right).

        For :math:`t\leq t_s` and :math:`x_m>0`, the temperature remains
        equal to :math:`T_0`.

        This solution provides a reference for validating the numerical
        forward model when the step time coincides with a time-grid point.
        """
        b_analytical = np.full(self.time.shape, self.T0, dtype=float)

        tau = self.time - time_step
        mask = tau > 0
        b_analytical[mask] += ((T_source - self.T0) * scipy.special.erfc(
            self.xm / (2 * np.sqrt(self.alpha * tau[mask]))))
        return b_analytical
    
    def kernel(self, tau):
        r"""
        Evaluate the heat kernel at the measurement position.

        Parameters
        ----------
        tau : ndarray, shape (N,)
            Time lags at which the kernel is evaluated, in s.

        Returns
        -------
        K : ndarray, shape (N,)
            Kernel values at the specified time lags, in 1/s.

        Notes
        -----
        The kernel relates the boundary-temperature rise to the
        temperature rise measured at :math:`x_m`:

        .. math::

            T(x_m,t)-T_0
            =
            \int_0^t
            K(x_m,t-s)[T_s(s)-T_0]\,ds.

        For a semi-infinite rod, the kernel is

        .. math::

            K(x_m,\tau)
            =
            \frac{x_m}
            {2\sqrt{\pi\alpha}\,\tau^{3/2}}
            \exp\left(
                -\frac{x_m^2}{4\alpha\tau}
            \right),
            \qquad \tau>0.

        The kernel is causal and is set to zero for
        :math:`\tau\leq 0` [1]_.

        The sensing matrix is constructed by integrating this kernel
        over the time intervals, rather than evaluating it at
        individual time lags.

        References
        ----------
        .. [1] H. S. Carslaw and J. C. Jaeger, Conduction of Heat in Solids, 2nd edition, 
            Clarendon Press, 1959.

        """
        K = np.zeros_like(tau)
        mask = tau > 0
        K[mask] = (self.xm/(2 * np.sqrt(np.pi * self.alpha) * tau[mask]**1.5))*\
            np.exp(-self.xm**2 / (4 * self.alpha * tau[mask]))
        return K

    def sens_mtx(self,):
        r"""
        Construct the sensing matrix using integrated heat-kernel weights.

        The boundary-temperature rise is approximated as piecewise constant
        over uniform time intervals. The heat kernel is integrated exactly
        over each interval to construct the discrete forward operator [1]_, [2]_.

        The resulting sensing matrix is stored in ``A``.

        Notes
        -----
        **Time discretization**

        Let the measurement times be

        .. math::

            t_i = i\Delta t,
            \qquad i=0,\ldots,N-1,

        where :math:`\Delta t=1/f_s`.

        The boundary-temperature rise is approximated by a constant
        :math:`u_j` over each interval

        .. math::

            [t_j,t_{j+1}),
            \qquad j=0,\ldots,N-2.

        Consequently, there are :math:`N` measurement instants but only
        :math:`N-1` unknown source values.

        **Integrated kernel weights**

        The cumulative integral of the heat kernel is

        .. math::

            F(\tau)
            =
            \operatorname{erfc}
            \left(
                \frac{x_m}{2\sqrt{\alpha\tau}}
            \right),
            \qquad \tau>0,

        with :math:`F(0)=0`.

        The exact kernel weights are

        .. math::

            w_k
            =
            F((k+1)\Delta t)-F(k\Delta t),
            \qquad k=0,\ldots,N-2.

        Integrating the kernel over each interval avoids the errors
        associated with evaluating a sharply peaked kernel at isolated
        time lags.

        **Sensing matrix**

        The discrete forward model is

        .. math::

            \mathbf{y}_{\mathrm{true}}
            =
            \mathbf{A}\mathbf{u}_{\mathrm{true}},

        where

        .. math::

            \mathbf{u}_{\mathrm{true}}
            =
            \mathbf{x}_{\mathrm{true}}-T_0\mathbf{1},

        and

        .. math::

            \mathbf{y}_{\mathrm{true}}
            =
            \mathbf{b}_{\mathrm{true}}-T_0\mathbf{1}.

        The matrix entries are

        .. math::

            A_{ij}
            =
            \begin{cases}
            w_{i-j-1}, & i>j,\\
            0, & i\leq j,
            \end{cases}

        for :math:`i=0,\ldots,N-1` and
        :math:`j=0,\ldots,N-2`.

        Thus,

        .. math::

            \mathbf{A}
            =
            \begin{bmatrix}
            0   & 0   & 0   & \cdots & 0 \\
            w_0 & 0   & 0   & \cdots & 0 \\
            w_1 & w_0 & 0   & \cdots & 0 \\
            w_2 & w_1 & w_0 & \cdots & 0 \\
            \vdots & \vdots & \vdots & \ddots & \vdots
            \end{bmatrix}
            \in \mathbb{R}^{N\times(N-1)}.

        The matrix is lower-triangular in the rectangular sense and
        has a Toeplitz structure: its entries are constant along
        each diagonal.

        **Inverse problem**

        The first row of :math:`\mathbf{A}` is zero because the
        measurement at :math:`t=0` equals the known initial temperature
        :math:`T_0` and contains no information about the boundary
        temperature history.

        For inversion, the first row and the corresponding measurement
        are removed:

        .. math::

            \mathbf{A}_{\mathrm{inv}}
            =
            \mathbf{A}[1:,:],

        .. math::

            \mathbf{y}
            =
            \mathbf{b}[1:]-T_0\mathbf{1}.

        The resulting system is

        .. math::

            \mathbf{A}_{\mathrm{inv}}\mathbf{u}
            \approx \mathbf{y},

        where :math:`\mathbf{A}_{\mathrm{inv}}` has shape
        :math:`(N-1,N-1)`.

        After estimating the boundary-temperature rise
        :math:`\mathbf{u}_{\mathrm{est}}`, the absolute boundary
        temperature is recovered as [2]_

        .. math::

            \mathbf{x}_{\mathrm{est}}
            =
            \mathbf{u}_{\mathrm{est}}+T_0\mathbf{1}.

            
        References
        ----------
        .. [1] H. S. Carslaw and J. C. Jaeger, Conduction of Heat in Solids, 2nd edition, 
            Clarendon Press, 1959.

        .. [2] J. V. Beck, B. Blackwell and C. R. St. Clair Jr., Inverse Heat Conduction: 
            Ill-Posed Problems, Wiley, 1985.
        """
        dt = self.time[1] - self.time[0]
        n = len(self.time)

        # Cumulative integral of the heat kernel.
        F = np.zeros(n)
        tau = self.time[1:]
        F[1:] = scipy.special.erfc(self.xm / (2 * np.sqrt(self.alpha * tau)))
        # Exact kernel integrals over consecutive time intervals.
        weights = np.diff(F)
        # Lower-triangular convolution matrix.
        # N measurements and N-1 unknown boundary intervals.
        self.A = scipy.linalg.toeplitz(np.concatenate(([0.0], weights)), np.zeros(n - 1))

    def temp_step(self, time_step=1.0, T_source=400.0):
        r"""
        Generate a step in the boundary-temperature history.

        The boundary temperature changes from the initial temperature
        :math:`T_0` to :math:`T_{\mathrm{source}}` at the specified time.


        Parameters
        ----------
        time_step : float, default=1.0
            Time at which the boundary temperature changes, in s.
        T_source : float, default=400.0
            Boundary temperature after the step, in K.

        Notes
        -----
        The prescribed boundary temperature is

        .. math::

            T_s(t) =
            \begin{cases}
            T_0, & t<t_s,\\
            T_{\mathrm{source}}, & t\geq t_s,
            \end{cases}

        where :math:`t_s` is ``time_step``.

        The absolute boundary-temperature history is stored in
        ``x_true``, with shape ``(N-1,)``. Each value is associated
        with an interval :math:`[t_j,t_{j+1})`.

        If ``time_step`` does not coincide with a time-grid point,
        the discrete step occurs at the first interval starting
        at or after the specified time.

        This source can be used with :func:`temp_analytical_step` to
        validate the numerical forward model.
        """
        self.x_true = np.full(self.time[:-1].shape, self.T0, dtype=float)
        self.x_true[self.time[:-1] >= time_step] = T_source
    
    def temp_square_pulse(self, time_init=1, time_end=2, T_source=400):
        r"""
        Generate a square pulse in the boundary-temperature history.

        The boundary temperature equals :math:`T_{\mathrm{source}}`
        during a specified time interval and :math:`T_0` elsewhere.

        Parameters
        ----------
        time_init : float, default=1
            Initial time of the pulse, in s.
        time_end : float, default=2
            Final time of the pulse, in s.
        T_source : float, default=400
            Boundary temperature during the pulse, in K.

        Notes
        -----
        The prescribed boundary temperature is

        .. math::

            T_s(t) =
            \begin{cases}
            T_{\mathrm{source}},
            & t_{\mathrm{init}}<t<t_{\mathrm{end}},\\
            T_0, & \text{otherwise}.
            \end{cases}

        The absolute boundary-temperature history is stored in
        ``x_true``, with shape ``(N-1,)``.

        The pulse is assigned according to the starting times of
        the source intervals, using strict inequalities at both
        ends.
        """
        self.x_true = np.full(self.time.shape[0]-1, self.T0, dtype=float)
        mask = (self.time[:-1] > time_init) & (self.time[:-1] < time_end)
        self.x_true[mask] = T_source
        
    def temp_hann_pulse(self, time_init=1.0, time_end=2.0, T_source=400.0):
        r"""
        Generate a Hann-shaped boundary-temperature pulse.

        The boundary temperature varies smoothly from :math:`T_0`
        toward :math:`T_{\mathrm{source}}` and returns to :math:`T_0`.

        Parameters
        ----------
        time_init : float, default=1.0
            Initial time of the pulse, in s.
        time_end : float, default=2.0
            Final time of the pulse, in s.
        T_source : float, default=400.0
            Nominal peak boundary temperature, in K.

        Notes
        -----
        For the source intervals selected by

        .. math::

            t_{\mathrm{init}}\leq t_j<t_{\mathrm{end}},

        the boundary temperature is

        .. math::

            T_{s,j}
            =
            T_0
            +
            (T_{\mathrm{source}}-T_0)w_j,

        where :math:`w_j` is a symmetric Hann window.

        Outside the selected intervals, the boundary temperature
        equals :math:`T_0`.

        The absolute boundary-temperature history is stored in
        ``x_true``, with shape ``(N-1,)``.

        For an even number of window samples, the symmetric Hann
        window does not reach exactly one. Consequently, the
        sampled peak temperature may be slightly below
        :math:`T_{\mathrm{source}}` for a heating pulse.
        """
        t_source = self.time[:-1]
        self.x_true = np.full(t_source.shape, self.T0, dtype=float)
        mask = (t_source >= time_init) & (t_source < time_end)
        n_pulse = np.count_nonzero(mask)
        if n_pulse > 0:
            window = scipy.signal.windows.hann(n_pulse)
            self.x_true[mask] = self.T0 + (T_source - self.T0) * window

    def temp_random(self, std_temp=20.0, seed=0):
        r"""
        Generate a random boundary-temperature history.

        The boundary temperature is independently sampled from a
        normal distribution over each source interval.

        Parameters
        ----------
        std_temp : float, default=20.0
            Standard deviation of the boundary temperature, in K.
        seed : int, default=0
            Seed for reproducible random samples.

        Notes
        -----
        The boundary-temperature values satisfy

        .. math::

            T_{s,j}
            \sim
            \mathcal{N}(T_0,\sigma_T^2),

        where :math:`\sigma_T` is ``std_temp``.

        The corresponding temperature rise is

        .. math::

            u_j = T_{s,j}-T_0,

        which has zero mean in expectation.

        The absolute boundary-temperature history is stored in
        ``x_true``, with shape ``(N-1,)``.

        A local NumPy random generator is used, so calling this
        method does not modify NumPy's global random state.
        """
        rng = np.random.default_rng(seed)
        self.x_true = rng.normal(loc=self.T0, scale=std_temp, size=len(self.time) - 1)
        
    def noiseless_meas(self):
        r"""
        Compute the noiseless temperature measurements.

        Evaluates the discrete forward model to obtain the absolute
        temperature history at the measurement position.

        Notes
        -----
        The sensing matrix maps boundary-temperature rise to measured
        temperature rise:

        .. math::

            \mathbf{y}_{\mathrm{true}}
            =
            \mathbf{A}\mathbf{u}_{\mathrm{true}},

        where

        .. math::

            \mathbf{u}_{\mathrm{true}}
            =
            \mathbf{x}_{\mathrm{true}}-T_0\mathbf{1}.

        The absolute measured temperature is recovered by adding the
        initial temperature:

        .. math::

            \mathbf{b}_{\mathrm{true}}
            =
            T_0\mathbf{1}
            +
            \mathbf{A}
            (\mathbf{x}_{\mathrm{true}}-T_0\mathbf{1}).

        The sensing matrix ``A``, with shape ``(N, N-1)``, must be
        constructed using ``sens_mtx``. The boundary-temperature history
        ``x_true``, with shape ``(N-1,)``, must also be initialized.

        The resulting noiseless measurement vector is stored in
        ``b_true``, with shape ``(N,)``, in K. Its first element equals
        :math:`T_0`.
        """
        self.b_true = self.T0 + self.A @ (self.x_true - self.T0)
        
    def add_noise(self, snr = 25, seed = 0):
        r"""
        Add Gaussian noise to the temperature measurements.

        Noise is generated relative to the measured temperature rise,
        rather than the absolute temperature, to achieve the prescribed
        signal-to-noise ratio (SNR).

        Parameters
        ----------
        snr : float, default=25
            Target signal-to-noise ratio, in dB.
        seed : int, default=0
            Seed for reproducible noise generation.

        Notes
        -----
        The noiseless measured temperature rise is

        .. math::

            \mathbf{y}_{\mathrm{true}}
            =
            \mathbf{b}_{\mathrm{true}}-T_0\mathbf{1}.

        Gaussian noise is added according to

        .. math::

            \mathbf{y}_{\mathrm{noisy}}
            =
            \mathbf{y}_{\mathrm{true}}+\mathbf{n},

        where :math:`\mathbf{n}` is scaled to achieve the prescribed
        SNR relative to :math:`\mathbf{y}_{\mathrm{true}}`.

        The absolute noisy temperature measurements are then

        .. math::

            \mathbf{b}_{\mathrm{noisy}}
            =
            T_0\mathbf{1}+\mathbf{y}_{\mathrm{noisy}}.

        The noiseless measurements must first be computed using
        ``noiseless_meas``.

        Noise generation is performed by
        :func:`~pyregtools.utils.reg_utils.add_gaussian_noise`.

        The resulting noisy measurement vector is stored in
        ``b_noisy``, with shape ``(N,)``, in K.
        """
        self.b_noisy = add_gaussian_noise(self.b_true-self.T0, snr = snr, seed = seed)
        self.b_noisy += self.T0