"""Iterative regularization methods for linear inverse problems.

This module provides iterative methods for solving linear inverse problems

.. math::

    A x \\simeq b,

where :math:`A \\in \\mathbb{C}^{M \\times L}` is the forward operator,
:math:`b \\in \\mathbb{C}^{M}` is the measured data, and
:math:`x \\in \\mathbb{C}^{L}` is the unknown solution.

For ill-posed problems, directly solving the least-squares problem may
produce solutions dominated by components associated with small singular
values of the forward operator. Iterative methods can provide regularized
solutions by terminating the iterations before convergence. In this
setting, the iteration number acts as a regularization parameter.

The methods implemented here include Landweber iteration,
Landweber--Cimmino iteration, the algebraic reconstruction technique
(ART, or Kaczmarz's method), and conjugate gradient least squares (CGLS). A good review
of such methods can be found in Ref. [1]_

Stationary iterative methods
----------------------------
The Landweber method updates the solution according to

.. math::

    x_{k+1}
    =
    x_k + \\omega A^H (b - A x_k),

where :math:`A^H` denotes the Hermitian transpose and :math:`\\omega` is
a relaxation parameter. The method gradually introduces components of
the solution associated with progressively smaller singular values.
Consequently, early iterations tend to emphasize the dominant spectral
components of the inverse problem, while later iterations may amplify
components associated with small singular values and measurement noise.

The Landweber--Cimmino method introduces a diagonal weighting matrix
:math:`D`,

.. math::

    x_{k+1}
    =
    x_k + \\omega A^H D (b - A x_k),

where the weights account for the norms of the rows of :math:`A`.

ART is a row-action method. Instead of using all measurements
simultaneously, it processes one equation

.. math::

    a_i x = b_i

at a time and projects the current solution onto the corresponding
solution hyperplane. One complete iteration, or sweep, processes all
rows of the forward problem.

Krylov-subspace methods
-----------------------
CGLS applies the conjugate-gradient method to the least-squares problem.
Starting from an initial solution :math:`x_0`, its iterates belong to
successively larger Krylov subspaces generated by the normal-equation
operator :math:`A^H A`. For :math:`x_0 = 0`,

.. math::

    x_k \\in
    \\mathcal{K}_k(A^H A, A^H b),

where

.. math::

    \\mathcal{K}_k(A^H A, A^H b)
    =
    \\operatorname{span}
    \\left\\{
    A^H b,
    (A^H A)A^H b,
    \\ldots,
    (A^H A)^{k-1}A^H b
    \\right\\}.

For many discrete ill-posed problems, the dominant spectral components
of the solution are captured in the early Krylov subspaces. Components
associated with small singular values typically become increasingly
important as the subspace grows. Thus, as with stationary iterative
methods, terminating CGLS sufficiently early can provide iterative
regularization.

Operator representations
------------------------
Landweber, Landweber--Cimmino, and CGLS can operate on explicit matrices
or on ``scipy.sparse.linalg.LinearOperator`` objects. This permits
matrix-free implementations when the actions of :math:`A` and
:math:`A^H` can be computed without explicitly assembling the forward
matrix.

ART requires access to individual equations of the forward problem. It
can therefore operate either on an explicit matrix or through a
user-supplied ``get_row`` callable that constructs row :math:`a_i` on
demand. This is useful for row-action forward models, such as
tomographic reconstruction problems, where individual measurement
operators can be generated without storing the complete sensing matrix.

Notes
-----
Iterative regularization commonly exhibits semi-convergence: the error
with respect to the unknown exact solution may initially decrease and
later increase as the iterations begin to reconstruct noise or other
unstable components of the data. Consequently, the iteration count and
the stopping criterion are important parts of the regularization
procedure.

References
----------
.. [1] P. C. Hansen, *Discrete Inverse Problems: Insight and Algorithms*,
       SIAM, 2010.
"""

import numpy as np
import scipy
import matplotlib.pyplot as plt
import warnings

def landweber(A, b, omega = 0.1, x0 = None, max_it = 50):
    """Solve a linear inverse problem using Landweber iteration.

    The Landweber method generates a sequence of approximate solutions to

    .. math::

        \\mathbf{A x} \\simeq \\mathbf{b}

    using the iteration

    .. math::

        \\mathbf{x}_{k+1}
        =
        \\mathbf{x}_k + \\omega \\mathbf{A}^H (\\mathbf{b} - \\mathbf{A x}_k),

    where :math:`A^H` denotes the Hermitian transpose of :math:`A` and
    :math:`\\omega` is a relaxation parameter.

    For convergence, the relaxation parameter must satisfy

    .. math::

        0 < \\omega < \\frac{2}{\\|\\mathbf{A}\\|_2^2}.

    For ill-posed problems, the iteration number can act as a regularization
    parameter. The iterations are typically terminated before convergence to
    limit the influence of components associated with small singular values
    and perturbations in the data [1]_.

    Parameters
    ----------
    A : ndarray, shape (M, L), or scipy.sparse.linalg.LinearOperator
        Forward operator. If given as a ``LinearOperator``, both its
        ``matvec`` and ``rmatvec`` operations must be defined.
    b : ndarray, shape (M,)
        Right-hand-side or measured data vector.
    omega : float, optional
        Relaxation parameter. It must be positive and, for an explicit
        matrix, satisfy :math:`\\omega < 2 / \\|A\\|_2^2`.
        Default is 0.1.
    x0 : ndarray, shape (L,), optional
        Initial solution. If ``None``, a zero vector is used.
        Default is ``None``.
    max_it : int, optional
        Maximum number of iterations. Default is 50.

    Returns
    -------
    x_sol : ndarray, shape (L, max_it)
        Solution history. Column ``k`` contains the approximate solution
        after iteration ``k + 1``.
    sol_norms : ndarray, shape (max_it,)
        Euclidean norm of the solution at each iteration.
    res_norms : ndarray, shape (max_it,)
        Euclidean norm of the residual :math:`A x_k - b` at each
        iteration.

    Notes
    -----
    Let the singular value decomposition of :math:`A` be

    .. math::

        \\mathbf{A} = \\mathbf{U} \\boldsymbol{\\Sigma} \\mathbf{V}^H,

    with singular values :math:`\\sigma_i`. For :math:`x_0 = 0`, the
    Landweber iterate can be expressed as

    .. math::

        \\mathbf{x}_k =
        \\sum_i
        \\left[1-(1-\\omega\\sigma_i^2)^k\\right]
        \\frac{\\mathbf{u}_i^H \\mathbf{b}}{\\sigma_i} \\mathbf{v}_i.

    Hence, the Landweber filter factors are

    .. math::

        \\phi_i^{(k)}
        =
        1-(1-\\omega\\sigma_i^2)^k.

    Components associated with larger singular values are generally
    introduced more rapidly, whereas components associated with small
    singular values enter the solution more slowly. Early termination
    can therefore suppress components associated with the small singular
    values that are most sensitive to perturbations in the data.

    As the iterations proceed, these components may increasingly
    contribute to the solution, leading to semi-convergence in the
    presence of noise. The iteration number therefore acts as a
    regularization parameter.

    When ``A`` is provided as a ``LinearOperator``, the upper convergence
    bound for ``omega`` is not checked because the spectral norm of the
    operator is not explicitly computed. The user is responsible for
    selecting a suitable relaxation parameter.

    Examples
    --------
    Using an explicit forward matrix:

    >>> A = np.array([[1.0, 0.0],
    ...               [0.0, 2.0]])
    >>> b = np.array([1.0, 2.0])
    >>> x_sol, sol_norms, res_norms = landweber(
    ...     A, b, omega=0.1, max_it=20
    ... )

    The forward model can also be supplied as a
    ``scipy.sparse.linalg.LinearOperator``. Both the forward operation
    :math:`A x` and the adjoint operation :math:`A^H y` must be provided:

    >>> from scipy.sparse.linalg import LinearOperator
    >>> A_mat = np.array([[1.0, 0.0],
    ...                   [0.0, 2.0]])
    >>> Aop = LinearOperator(
    ...     shape=A_mat.shape,
    ...     matvec=lambda x: A_mat @ x,
    ...     rmatvec=lambda y: A_mat.conj().T @ y,
    ...     dtype=A_mat.dtype,
    ... )
    >>> x_sol, sol_norms, res_norms = landweber(
    ...     Aop, b, omega=0.1, max_it=20
    ... )

    While this is a simple usage example, the examples in the PyRegTools notebooks will deal 
    with more realistic cases, where building a full matrix :math:`\\mathbf{A}` is not desired.

    References
    ----------
    .. [1] P. C. Hansen, *Discrete Inverse Problems: Insight and
           Algorithms*, SIAM, 2010.
    """
    if omega <= 0:
        raise ValueError("omega must be positive.")
    b = np.asarray(b)
    is_operator = isinstance(A, scipy.sparse.linalg.LinearOperator)
    Aop = scipy.sparse.linalg.aslinearoperator(A)
    if not is_operator:
        A_norm = np.linalg.norm(A, ord=2)
        omega_max = 2.0 / A_norm**2
        if omega >= omega_max:
            raise ValueError(f"omega must satisfy 0 < omega < {omega_max:.6e}.")

    dtype = np.result_type(Aop.dtype, b.dtype)
    if x0 is None:
        x0 = np.zeros(Aop.shape[1], dtype=dtype)
    else:
        x0 = np.asarray(x0)
        dtype = np.result_type(dtype, x0.dtype)
        x0 = np.asarray(x0, dtype=dtype)

    # initialize solution vector, residual norm vector and sol. norm vector
    x_sol = np.zeros((Aop.shape[1], max_it), dtype=dtype)
    res_norms = np.zeros(max_it)
    sol_norms = np.zeros(max_it)
    xk = np.copy(x0)
    # loop
    for k in range(max_it):
        rk = b - Aop.matvec(xk)
        xk += omega * Aop.rmatvec(rk)
        x_sol[:,k] = xk
        sol_norms[k] = np.linalg.norm(xk)
        res_norms[k] = np.linalg.norm(Aop.matvec(xk)-b)
    return x_sol, sol_norms, res_norms

def landweber_cimmino(A, b, D=None, omega=0.1, x0=None, max_it=50):
    """Solve a linear inverse problem using Landweber--Cimmino iteration.

    The Landweber--Cimmino method generates a sequence of approximate
    solutions to

    .. math::

        \\mathbf{Ax} \\simeq \\mathbf{b}

    using the iteration

    .. math::

        \\mathbf{x}_{k+1}
        =
        \\mathbf{x}_k
        + \\omega \\mathbf{A}^H \\mathbf{D}
        (\\mathbf{b} - \\mathbf{A}\\mathbf{x}_k),

    where :math:`\\mathbf{A}^H` denotes the Hermitian transpose of
    :math:`\\mathbf{A}`, :math:`\\omega` is a relaxation parameter, and
    :math:`\\mathbf{D}` is a diagonal weighting matrix.

    The diagonal weights are defined as

    .. math::

        D_{ii}
        =
        \\frac{1}{M \\|\\mathbf{a}_i\\|_2^2},

    for nonzero rows :math:`\\mathbf{a}_i` of :math:`\\mathbf{A}`. A zero
    weight is assigned to zero rows.

    For ill-posed problems, the iteration number can act as a
    regularization parameter. The iterations are typically terminated
    before convergence to limit the influence of unstable components and
    perturbations in the data [1]_.

    Parameters
    ----------
    A : ndarray, shape (M, L), or scipy.sparse.linalg.LinearOperator
        Forward operator. If given as a ``LinearOperator``, both its
        ``matvec`` and ``rmatvec`` operations must be defined.
    b : ndarray, shape (M,)
        Right-hand-side or measured data vector.
    D : ndarray, shape (M,), optional
        Diagonal entries of the Cimmino weighting matrix
        :math:`\\mathbf{D}`. If ``None`` and ``A`` is an explicit matrix,
        the weights are computed from the row norms of ``A``. When ``A``
        is a ``LinearOperator``, ``D`` must be provided.
        Default is ``None``.
    omega : float, optional
        Relaxation parameter. It must be positive and, for an explicit
        matrix, satisfy

        .. math::

            0 < \\omega
            <
            \\frac{2}
            {\\|\\mathbf{D}^{1/2}\\mathbf{A}\\|_2^2}.

        Default is 0.1.
    x0 : ndarray, shape (L,), optional
        Initial solution. If ``None``, a zero vector is used.
        Default is ``None``.
    max_it : int, optional
        Maximum number of iterations. Default is 50.

    Returns
    -------
    x_sol : ndarray, shape (L, max_it)
        Solution history. Column ``k`` contains the approximate solution
        after iteration ``k + 1``.
    sol_norms : ndarray, shape (max_it,)
        Euclidean norm of the solution at each iteration.
    res_norms : ndarray, shape (max_it,)
        Euclidean norm of the residual
        :math:`\\mathbf{A}\\mathbf{x}_k - \\mathbf{b}` at each iteration.

    Notes
    -----
    Cimmino weighting scales the contribution of each equation according
    to the norm of the corresponding row of the forward operator. With

    .. math::

        \\mathbf{B} = \\mathbf{D}^{1/2}\\mathbf{A},

    the iteration can be interpreted as a Landweber iteration involving
    the weighted normal-equation operator

    .. math::

        \\mathbf{A}^H\\mathbf{D}\\mathbf{A}
        =
        \\mathbf{B}^H\\mathbf{B}.

    Consequently, the convergence condition is governed by the spectral
    norm of :math:`\\mathbf{D}^{1/2}\\mathbf{A}` rather than by the
    spectral norm of :math:`\\mathbf{A}` alone.

    As with standard Landweber iteration, early termination provides
    regularization. Later iterations may increasingly reconstruct
    components that are sensitive to noise, leading to semi-convergence.

    When ``A`` is provided as a ``LinearOperator``, its rows are not
    explicitly available. Therefore, the Cimmino weights cannot be
    constructed automatically and ``D`` must be supplied by the user.
    The upper convergence bound for ``omega`` is also not checked in
    this case.

    Examples
    --------
    Using an explicit forward matrix, the Cimmino weights are computed
    automatically:

    >>> A = np.array([[1.0, 0.0],
    ...               [1.0, 2.0]])
    >>> b = np.array([1.0, 2.0])
    >>> x_sol, sol_norms, res_norms = landweber_cimmino(
    ...     A, b, omega=0.1, max_it=20
    ... )

    The forward model can also be supplied as a
    ``scipy.sparse.linalg.LinearOperator``. In this case, the diagonal
    weights must be provided:

    >>> from scipy.sparse.linalg import LinearOperator
    >>> A_mat = np.array([[1.0, 0.0],
    ...                   [1.0, 2.0]])
    >>> Aop = LinearOperator(
    ...     shape=A_mat.shape,
    ...     matvec=lambda x: A_mat @ x,
    ...     rmatvec=lambda y: A_mat.conj().T @ y,
    ...     dtype=A_mat.dtype,
    ... )
    >>> D = get_D_for_cimmino(A_mat)
    >>> x_sol, sol_norms, res_norms = landweber_cimmino(
    ...     Aop, b, D=D, omega=0.1, max_it=20
    ... )

    While this is a simple usage example, the examples in the PyRegTools notebooks will deal 
    with more realistic cases, where building a full matrix :math:`\\mathbf{A}` is not desired.

    References
    ----------
    .. [1] P. C. Hansen, *Discrete Inverse Problems: Insight and
           Algorithms*, SIAM, 2010.
    """
    if omega <= 0:
        raise ValueError("omega must be positive.")
    b = np.asarray(b)
    is_operator = isinstance(A, scipy.sparse.linalg.LinearOperator)
    Aop = scipy.sparse.linalg.aslinearoperator(A)

    if D is None:
        D = get_D_for_cimmino(A)
    else:
        D = np.asarray(D)

    if not is_operator:
        A_norm = np.linalg.norm(A, ord=2)
        B = np.sqrt(D)[:, None] * A
        B_norm = np.linalg.norm(B, ord=2)
        omega_max = 2.0 / B_norm**2
        if omega >= omega_max:
            raise ValueError(f"omega must satisfy 0 < omega < {omega_max:.6e}.")

    dtype = np.result_type(Aop.dtype, b.dtype)
    if x0 is None:
        x0 = np.zeros(Aop.shape[1], dtype=dtype)
    else:
        x0 = np.asarray(x0)
        dtype = np.result_type(dtype, x0.dtype)
        x0 = np.asarray(x0, dtype=dtype)

    # initialize solution vector, residual norm vector and sol. norm vector
    x_sol = np.zeros((Aop.shape[1], max_it), dtype=dtype)
    res_norms = np.zeros(max_it)
    sol_norms = np.zeros(max_it)
    xk = np.copy(x0)
    # loop
    for k in range(max_it):
        rk = b - Aop.matvec(xk)
        xk += omega * Aop.rmatvec(D * rk)
        x_sol[:,k] = xk
        sol_norms[k] = np.linalg.norm(xk)
        res_norms[k] = np.linalg.norm(Aop.matvec(xk)-b)
    return x_sol, sol_norms, res_norms

def get_D_for_cimmino(A):
    """Compute the diagonal weights for the Cimmino iteration.

    The weights are defined as

    .. math::

        D_{ii} =
        \\frac{1}{M \\|\\mathbf{a}_i\\|_2^2},

    where :math:`\\mathbf{a}_i` is the ``i``-th row of
    :math:`\\mathbf{A}`. Zero rows are assigned a zero weight.

    Parameters
    ----------
    A : ndarray, shape (M, L)
        Forward matrix.

    Returns
    -------
    D : ndarray, shape (M,)
        Diagonal entries of the Cimmino weighting matrix
        :math:`\\mathbf{D}`.

    Notes
    -----
    The weights cannot be computed from a
    ``scipy.sparse.linalg.LinearOperator`` because its individual rows
    are not explicitly available.
    """
    is_operator = isinstance(A, scipy.sparse.linalg.LinearOperator)
    if is_operator:
        raise ValueError("D can not be computed when A is a LinearOperator. It should be provided.")
    row_norms = np.linalg.norm(A, axis=1)
    D = np.zeros(A.shape[0])
    nonzero = row_norms > 0
    D[nonzero] = 1.0 / (A.shape[0] * row_norms[nonzero]**2)
    return D


def art_solver(b, A=None, get_row=None, n_unknowns=None,
               x0=None, max_it=50):
    """Solve a linear inverse problem using ART (Kaczmarz's method).

    The Algebraic Reconstruction Technique (ART), also known as
    Kaczmarz's method, is a row-action iterative method for solving

    .. math::

        \\mathbf{A}\\mathbf{x} \\simeq \\mathbf{b}.

    Instead of using all equations simultaneously, ART processes one
    equation at a time. For row :math:`\\mathbf{a}_i` of
    :math:`\\mathbf{A}`, the update is

    .. math::

        \\mathbf{x}
        \\leftarrow
        \\mathbf{x}
        +
        \\frac{
            b_i - \\mathbf{a}_i \\mathbf{x}
        }{
            \\|\\mathbf{a}_i\\|_2^2
        }
        \\mathbf{a}_i^H,

    where :math:`\\mathbf{a}_i^H` denotes the Hermitian transpose of the
    row vector. A complete sweep through all measurements constitutes one
    iteration.

    Geometrically, each row update projects the current solution onto the
    hyperplane defined by

    .. math::

        \\mathbf{a}_i\\mathbf{x} = b_i.

    For ill-posed problems, the iteration number can act as a
    regularization parameter. The iterations may be terminated before
    convergence to limit the influence of unstable components and
    perturbations in the data [1]_.

    Parameters
    ----------
    b : ndarray, shape (M,)
        Right-hand-side or measured data vector.
    A : ndarray, shape (M, L), optional
        Explicit forward matrix. If provided, its rows are used directly
        by the ART iteration. Either ``A`` or ``get_row`` must be
        provided. Default is ``None``.
    get_row : callable, optional
        Function that returns row ``i`` of the forward problem as a
        one-dimensional array of shape ``(L,)``. This allows ART to
        operate without explicitly constructing the complete forward
        matrix. Either ``A`` or ``get_row`` must be provided.
        Default is ``None``.
    n_unknowns : int, optional
        Number of unknowns :math:`L`. Required when ``get_row`` is used
        without an explicit matrix. When ``A`` is provided, this value
        is obtained from ``A.shape[1]``. Default is ``None``.
    x0 : ndarray, shape (L,), optional
        Initial solution. If ``None``, a zero vector is used.
        Default is ``None``.
    max_it : int, optional
        Maximum number of complete sweeps through the measurements.
        Default is 50.

    Returns
    -------
    x_sol : ndarray, shape (L, max_it)
        Solution history. Column ``k`` contains the approximate solution
        after sweep ``k + 1``.
    sol_norms : ndarray, shape (max_it,)
        Euclidean norm of the solution after each complete sweep.
    res_norms : ndarray, shape (max_it,)
        Euclidean norm of the residual
        :math:`\\mathbf{A}\\mathbf{x}_k - \\mathbf{b}` after each
        complete sweep.

    Notes
    -----
    ART differs from methods such as Landweber iteration in that the
    solution is updated sequentially using individual equations. Within
    a sweep, each row therefore acts on the solution produced by the
    preceding row.

    For consistent systems, each row update is an orthogonal projection
    onto the corresponding solution hyperplane. For inconsistent or
    noisy systems, the hyperplanes generally do not share a common
    intersection, and the behavior of the iterates depends on the
    sequential row projections.

    Early termination can provide iterative regularization. In inverse
    problems with noisy or perturbed data, the reconstruction error may
    initially decrease and subsequently increase as further sweeps
    introduce unstable components, resulting in semi-convergence.

    Zero rows of the forward problem are skipped.

    The ``get_row`` interface is useful when individual measurement
    equations can be generated on demand. For example, in computed
    tomography a row may contain the intersection lengths of one ray
    with the pixels of the discretized attenuation image. ART can then
    process each ray without storing the complete sensing matrix.

    Examples
    --------
    Using an explicit forward matrix:

    >>> A = np.array([[1.0, 0.0],
    ...               [1.0, 1.0]])
    >>> b = np.array([1.0, 2.0])
    >>> x_sol, sol_norms, res_norms = art_solver(
    ...     b, A=A, max_it=20
    ... )

    Alternatively, rows of the forward problem can be supplied on
    demand:

    >>> def get_row(i):
    ...     return A[i, :]
    >>> x_sol, sol_norms, res_norms = art_solver(
    ...     b,
    ...     get_row=get_row,
    ...     n_unknowns=A.shape[1],
    ...     max_it=20,
    ... )

    While this is a simple usage example, the examples in the PyRegTools notebooks will deal 
    with more realistic cases, where building a full matrix :math:`\\mathbf{A}` is not desired.

    References
    ----------
    .. [1] P. C. Hansen, *Discrete Inverse Problems: Insight and
           Algorithms*, SIAM, 2010.
    """
    b = np.asarray(b)
    if A is None and get_row is None:
        raise ValueError("Either A or get_row must be provided.")
    if A is not None and get_row is not None:
        raise ValueError("Provide either A or get_row, not both.")
    if A is not None:
        n_unknowns = A.shape[1]
        dtype = np.result_type(A.dtype, b.dtype)
        get_row = lambda i: A[i, :]
    else:
        if n_unknowns is None:
            raise ValueError("n_unknowns must be provided when using get_row.")
        a0 = np.asarray(get_row(0))
        dtype = np.result_type(a0.dtype, b.dtype)
    if x0 is None:
        x0 = np.zeros(n_unknowns, dtype=dtype)
    else:
        x0 = np.asarray(x0)
        dtype = np.result_type(dtype, x0.dtype)
        x0 = np.asarray(x0, dtype=dtype)

    x_sol = np.zeros((n_unknowns, max_it), dtype=dtype)
    res_norms = np.zeros(max_it)
    sol_norms = np.zeros(max_it)
    xk = np.copy(x0)
    # loop through iterations
    for k in range(max_it):
        # loop through the measurements
        for i in range(len(b)):
            a_i = np.asarray(get_row(i))
            row_norm2 = np.linalg.norm(a_i)**2
            if row_norm2 == 0:
                continue
            scale = (b[i] - a_i @ xk) / row_norm2
            xk += scale * np.conj(a_i)
        x_sol[:,k] = xk
        sol_norms[k] = np.linalg.norm(xk)
        # Residual norm after the complete sweep
        res_norm2 = 0.0
        for i in range(len(b)):
            a_i = np.asarray(get_row(i))
            ri = a_i @ xk - b[i]
            res_norm2 += np.abs(ri)**2
        res_norms[k] = np.sqrt(res_norm2)
    return x_sol, sol_norms, res_norms

def cgls(A, b, x0=None, max_it=50):
    """Solve a linear least-squares problem using CGLS.

    The Conjugate Gradient Least-Squares (CGLS) method generates a
    sequence of approximate solutions to

    .. math::

        \\mathbf{A}\\mathbf{x} \\simeq \\mathbf{b}

    by applying the conjugate-gradient method to the normal equations

    .. math::

        \\mathbf{A}^H \\mathbf{A}\\mathbf{x}
        =
        \\mathbf{A}^H \\mathbf{b},

    where :math:`\\mathbf{A}^H` denotes the Hermitian transpose of
    :math:`\\mathbf{A}`.

    CGLS constructs the solution in a sequence of Krylov subspaces.
    For :math:`\\mathbf{x}_0 = \\mathbf{0}`, the ``k``-th iterate belongs
    to

    .. math::

        \\mathcal{K}_k
        (\\mathbf{A}^H\\mathbf{A}, \\mathbf{A}^H\\mathbf{b})
        =
        \\operatorname{span}
        \\left\\{
        \\mathbf{A}^H\\mathbf{b},
        (\\mathbf{A}^H\\mathbf{A})\\mathbf{A}^H\\mathbf{b},
        \\ldots,
        (\\mathbf{A}^H\\mathbf{A})^{k-1}\\mathbf{A}^H\\mathbf{b}
        \\right\\}.

    For ill-posed problems, the iteration number can act as a
    regularization parameter. The iterations are typically terminated
    before convergence to limit the influence of unstable components
    and perturbations in the data [1]_.

    Parameters
    ----------
    A : ndarray, shape (M, L), or scipy.sparse.linalg.LinearOperator
        Forward operator. If given as a ``LinearOperator``, both its
        ``matvec`` and ``rmatvec`` operations must be defined.
    b : ndarray, shape (M,)
        Right-hand-side or measured data vector.
    x0 : ndarray, shape (L,), optional
        Initial solution. If ``None``, a zero vector is used.
        Default is ``None``.
    max_it : int, optional
        Maximum number of iterations. Default is 50.

    Returns
    -------
    x_sol : ndarray, shape (L, n_it)
        Solution history. Column ``k`` contains the approximate solution
        after iteration ``k + 1``. The number of completed iterations
        ``n_it`` may be smaller than ``max_it`` if the algorithm
        terminates early.
    sol_norms : ndarray, shape (n_it,)
        Euclidean norm of the solution at each completed iteration.
    res_norms : ndarray, shape (n_it,)
        Euclidean norm of the residual
        :math:`\\mathbf{b} - \\mathbf{A}\\mathbf{x}_k` at each completed
        iteration.

    Notes
    -----
    CGLS does not explicitly form the normal-equation matrix
    :math:`\\mathbf{A}^H\\mathbf{A}`. Instead, its action is obtained
    through successive applications of :math:`\\mathbf{A}` and
    :math:`\\mathbf{A}^H`. This is particularly useful for large-scale
    problems and matrix-free forward models.

    For many discrete ill-posed problems, the early Krylov subspaces
    preferentially capture components associated with the dominant
    singular values of :math:`\\mathbf{A}`. Components associated with
    smaller singular values generally become more influential as the
    Krylov subspace expands. Early termination can therefore suppress
    unstable components that would otherwise amplify perturbations in
    the data.

    This behavior can lead to semi-convergence: the reconstruction error
    may initially decrease and subsequently increase even though the
    residual norm continues to decrease. Consequently, convergence of
    the iterative algorithm does not necessarily correspond to the most
    useful regularized solution.

    The implementation terminates if
    :math:`\\|\\mathbf{A}^H\\mathbf{r}_k\\|_2 = 0`, indicating that the
    normal equations are satisfied. It also terminates with a
    ``RuntimeWarning`` if a nonzero search direction satisfies
    :math:`\\mathbf{A}\\mathbf{d}_k = \\mathbf{0}`.

    Examples
    --------
    Using an explicit forward matrix:

    >>> A = np.array([[1.0, 0.0],
    ...               [0.0, 2.0]])
    >>> b = np.array([1.0, 2.0])
    >>> x_sol, sol_norms, res_norms = cgls(
    ...     A, b, max_it=20
    ... )

    The forward model can also be supplied as a
    ``scipy.sparse.linalg.LinearOperator``. Both the forward operation
    :math:`\\mathbf{A}\\mathbf{x}` and the adjoint operation
    :math:`\\mathbf{A}^H\\mathbf{y}` must be provided:

    >>> from scipy.sparse.linalg import LinearOperator
    >>> A_mat = np.array([[1.0, 0.0],
    ...                   [0.0, 2.0]])
    >>> Aop = LinearOperator(
    ...     shape=A_mat.shape,
    ...     matvec=lambda x: A_mat @ x,
    ...     rmatvec=lambda y: A_mat.conj().T @ y,
    ...     dtype=A_mat.dtype,
    ... )
    >>> x_sol, sol_norms, res_norms = cgls(
    ...     Aop, b, max_it=20
    ... )

    While this is a simple usage example, the examples in the PyRegTools notebooks will deal 
    with more realistic cases, where building a full matrix :math:`\\mathbf{A}` is not desired.

    References
    ----------
    .. [1] P. C. Hansen, *Discrete Inverse Problems: Insight and
           Algorithms*, SIAM, 2010.
    """
    b = np.asarray(b)
    Aop = scipy.sparse.linalg.aslinearoperator(A)
    # Handle complex or real data
    dtype = np.result_type(Aop.dtype, b.dtype)
    if x0 is None:
        x0 = np.zeros(Aop.shape[1], dtype=dtype)
    else:
        x0 = np.asarray(x0)
        dtype = np.result_type(dtype, x0.dtype)
        x0 = np.asarray(x0, dtype=dtype)

    #Ah = A.conj().T # Hermitian of A
    # initialize solution vector
    x_sol = np.zeros((Aop.shape[1], max_it), dtype = dtype)
    res_norms = np.zeros(max_it)
    sol_norms = np.zeros(max_it)
    xk = np.copy(x0)
    # loop
    #rk = b - A @ xk
    #dk = Ah @ rk
    rk = b - Aop.matvec(xk)
    dk = Aop.rmatvec(rk)
    normr2 = np.linalg.norm(dk)**2

    n_it = 0
    for k in range(max_it):
        # Exact convergence
        if normr2 == 0:
            break
        #Ad = A @ dk
        Ad = Aop.matvec(dk)
        normAd2 = np.linalg.norm(Ad)**2
        # Breakdown
        if normAd2 == 0:
            warnings.warn("CGLS iteration terminated because the search direction "
            "satisfies A @ d = 0.",RuntimeWarning)
            break

        alphak = normr2/normAd2
        xk += alphak * dk
        rk -= alphak * Ad #A @ dk
        #sk = Ah @ rk
        sk = Aop.rmatvec(rk)
        normr2_new = np.linalg.norm(sk)**2
        betak = normr2_new/normr2
        normr2 = normr2_new
        dk = sk + betak * dk
        # fill returns
        x_sol[:,k] = xk
        res_norms[k] = np.linalg.norm(rk)
        sol_norms[k] = np.linalg.norm(xk)
        n_it = k + 1
    return x_sol[:, :n_it], sol_norms[:n_it], res_norms[:n_it]


def art_solver0(A, b, x0 = None, max_it = 50):
    """ Kaczmarz’s method or Algebraic Reconstruction Technique (ART)
    
    As in Sec 6.1.2 of Discrete Inverse Problems
    """
    # Data Handling
    b = np.asarray(b)
    dtype = np.result_type(A.dtype, b.dtype)

    if x0 is None:
        x0 = np.zeros(A.shape[1], dtype=dtype)
    else:
        x0 = np.asarray(x0)
        dtype = np.result_type(dtype, x0.dtype)
        x0 = np.asarray(x0, dtype=dtype)

    # initialize solution vector
    x_sol = np.zeros((A.shape[1], max_it), dtype=dtype)
    res_norms = np.zeros(max_it)
    sol_norms = np.zeros(max_it)
    xk = np.copy(x0)
    # loop through iterations
    for k in range(max_it):
        # loop through rows of A
        for i in range(A.shape[0]):
            a_i = A[i, :]
            row_norm2 = np.linalg.norm(a_i)**2
            if row_norm2 == 0:
                continue
            scale = (b[i] - a_i @ xk) / row_norm2
            xk += scale * np.conj(a_i)
        x_sol[:,k] = xk
        sol_norms[k] = np.linalg.norm(xk)
        res_norms[k] = np.linalg.norm(A @ xk - b)
    return x_sol, sol_norms, res_norms


class IterativeSolvers(object):
    """ Solve regularized problems with iterative solvers
    """
    def __init__(self, A, b, x0 = None):
        self.A = A
        self.m = self.A.shape[0]
        self.n = self.A.shape[1]
        self.b = b
        if x0 is None:
            self.x0 = np.zeros(self.A.shape[1], dtype = complex)
        else:
            self.x0 = x0
            
    def init_vars(self, ):
        self.xk = np.copy(self.x0)
        self.x_sol = np.zeros((self.n, self.max_it), dtype = complex)
        self.res_norms = np.zeros(self.max_it)
        self.sol_norms = np.zeros(self.max_it)
            
    def landweber_cimmino(self, omega = 0.1, max_it = 50, cimmino = False):
        """ Landweber iterative solver
        
        As in Eq. (6.1) of Discrete Inverse Problems
        """
        self.max_it = max_it
        self.omega = omega
        Ah = np.conj(self.A.T) # Hermitian of A
        AhA_norm = np.linalg.norm(Ah @ self.A)
        # Check omega
        if self.omega<=0 or self.omega>=2/AhA_norm:
            raise ValueError(r"$\omega$ must be a value between 0 and {}".format(2/AhA_norm))   
        # initialize variables
        self.init_vars()
        if cimmino:
            D = self.get_Dmtx()
            Ah = Ah @ np.diag(D)
        # loop
        for k in range(self.max_it):
            rk = self.b - self.A @ self.xk
            self.xk += self.omega * Ah @ rk
            self.x_sol[:,k] = self.xk
            self.res_norms[k] = np.linalg.norm(rk)
            self.sol_norms[k] = np.linalg.norm(self.xk)
            
    def get_Dmtx(self):
        """ Get D matrix for Cimmmino iterative solver
        """
        # matrix D
        D = np.zeros(self.m)
        for row in range(self.m):
            if not np.any(self.A[row,:]):
                D[row] = 0
            else:
                row_norm = np.linalg.norm(self.A[row,:])
                D[row] = 1/(self.m*row_norm**2)
        return D
    
    def art_solver(self, max_it = 50):
        """ Kaczmarz’s method or Algebraic Reconstruction Technique (ART)
        
        As in Sec 6.1.2 of Discrete Inverse Problems
        """
        self.max_it = max_it
        # initialize variables
        self.init_vars()
        # loop through iterations
        for k in range(self.max_it):
            # loop through rows of A
            for i in range(self.m):
                a_i = self.A[i,:]
                scale = (self.b[i]-np.conj(a_i) @ self.xk)/(np.linalg.norm(a_i)**2)
                self.xk += scale * a_i
            self.x_sol[:,k] = self.xk
            self.res_norms[k] = np.linalg.norm(self.A @ self.xk - self.b)
            self.sol_norms[k] = np.linalg.norm(self.xk)
        
    def cgls(self, max_it = 50):
        """ Conjugate Gradient Least-Squares
        
        As in Sec 6.3.2 of Discrete Inverse Problems
        """
        self.max_it = max_it
        Ah = np.conj(self.A.T) # Hermitian of A
        # initialize solution vector
        # initialize variables
        self.init_vars()
        # loop
        rk = self.b - self.A @ self.xk
        dk = Ah @ rk
        normr2 = np.linalg.norm(dk)**2
        for k in range(max_it):
            # past_residual = residual
            # d_k = Ah @ residual 
            Ad = self.A @ dk
            alphak = normr2/(np.linalg.norm(Ad)**2)
            self.xk += alphak * dk
            rk -= alphak * Ad #A @ dk
            sk = Ah @ rk
            normr2_new = np.linalg.norm(sk)**2
            betak = normr2_new/normr2
            normr2 = normr2_new
            dk = sk + betak * dk
            # fill returns
            self.x_sol[:,k] = self.xk
            self.res_norms[k] = np.linalg.norm(rk)
            self.sol_norms[k] = np.linalg.norm(self.xk)

    def plot_l(self, xlim = None, ylim = None):
        """ plots L-curve along iterations
        """
        if xlim is None:
            xlim = (0.9*self.res_norms.min(), 1.1*self.res_norms.max())
        if ylim is None:
            ylim = (0.9*self.sol_norms.min(), 1.1*self.sol_norms.max())
        
        plt.figure(figsize = (6,3))
        plt.loglog(self.res_norms, self.sol_norms, 'o-k', alpha = 0.8, markersize = 3)
        plt.xlim(xlim)
        plt.ylim(ylim)
        plt.grid(linestyle = '--')
        plt.xlabel(r"$\left\|\mathbf{Ax}-\mathbf{b}\right\|$")
        plt.ylabel(r"$\left\|\mathbf{x}\right\|$")

        plt.tight_layout()
        
    def plot_error_history(self, x_true):
        """ plots error history vs. iterations
        """
        error = self.x_sol - np.reshape(np.repeat(x_true, self.max_it), (self.n, self.max_it))
        e = np.linalg.norm(error, axis = 0)
        plt.figure(figsize = (6,3))
        plt.semilogy(e, 'o-k', markersize = 3)
        plt.grid(linestyle = '--')
        plt.xlabel(r"Iterations $k$ [-]")
        plt.ylabel(r"$\left\|\mathbf{x}_{\text{True}} - \mathbf{x}_{\text{sol}}\right\|$")
        plt.tight_layout()